apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accesModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    type: ext4
    volumeHandle: vol-0338ddebd3dc7a407