apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic-pod
  labels:
    purpose: "ebs-sc-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  volumes:
  - name: persistent-volume  
    persistentVolumeClaim:
      claimName: dynamic-pvc
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-volume
      mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-lb-service-dynamic
spec:
  type: LoadBalancer
  selector:
    purpose: "ebs-sc-demo"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
