apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  volumeMode: FileSystem
  storageClassName: ""
  persistentVolumeClaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    type: ext4
    volumeHandle: fs-09455ccfe1c017efe
