apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-static
spec:
  storageClassName: ""
  volumeName: "efs-static"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static-pod
  labels:
    purpose: "efs-static-demo"
spec:
  volumes:
  - name: persitent-volume
    persistentVolumeClaim:
      claimName: efs-pvc-static
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persitent-volume
      mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: efs-static-service
spec:
  type: LoadBalancer
  selector:
    purpose: "efs-static-demo"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
