apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-dynamic
spec:
  storageClassName: efs-sc
  accesModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic-pod
  labels:
    purpose: "efs-dynamic-demo"
spec:
  conatiners:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ps-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ps
    persistentVolumeClaim:
      claimName: efs-pvc-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: efs-service
spec:
  type: LoadBalancer
  selector:
    purpose: "efs-dynamic-demo"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009