apiVersion: v1
kind: Service
metadata:
  name: myservice-nodeport
spec:
  type: NodePort
  selector:
    project: demo
    environment: dev
    servicetype: nodeport
  ports:
    protocol: tcp
    port: 80 # service port
    targetPort: 80 # target container port
    nodePort: 30020
---
apiVersion: v1
kind: Pod
metadata:
  name: service-np-pod
  labels:
    project: demo
    environment: dev
    servicetype: nodeport
spec:
  containers:
  - name: nginx
    image: nginx