apiVersion: v1
kind: Service
metadata:
  name: myservice-lb
spec:
  type: LoadBalancer
  selector:
    projec: demo
    environment: dev
    servicetype: loadbalancer
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # target container port
    nodePort: 30007
---
apiVersion: v1
kind: Pod
metadata:
  name: service-lb-pod
  labels:
    project: demo
    environment: dev
    servicetype: loadbalancer
spec:
  containers:
  - name: nginx
    image: nginx